plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - LICENSE.md

title: Quest Modding Tools
description: Tools for modding Quest applications.
baseurl: "/Quest-Modding-Tools"
url: "https://sc2ad.github.io"

permalink: pretty

theme: just-the-docs
